const $=id=>document.getElementById(id);
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
const compact=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2});
const integer=new Intl.NumberFormat('en-US');
let data=[],regions=[];
const sum=(rows,key)=>rows.reduce((s,r)=>s+r[key],0);
function group(rows,key){const map=new Map();for(const row of rows){const name=row[key];if(!map.has(name))map.set(name,{name,sales:0,profit:0,lines:0});const v=map.get(name);v.sales+=row.sales;v.profit+=row.profit;v.lines+=row.lines;}return [...map.values()].map(r=>({...r,margin:r.sales?100*r.profit/r.sales:0}));}
function bars(id,rows,key,format){const root=$(id);root.replaceChildren();const max=Math.max(...rows.map(r=>Math.abs(r[key])),1);for(const r of rows){const el=document.createElement('div');el.className='bar-row';const label=document.createElement('span');label.textContent=r.name;const track=document.createElement('div');track.className='bar-track';const fill=document.createElement('div');fill.className='bar-fill'+(r[key]<0?' negative':'');fill.style.width=(Math.abs(r[key])/max*100)+'%';track.append(fill);const value=document.createElement('span');value.className='bar-value';value.textContent=format(r[key]);el.append(label,track,value);root.append(el);}}
function render(){const rows=data.filter(r=>($('year').value==='all'||r.year===Number($('year').value))&&($('region').value==='all'||r.region===$('region').value)&&($('category').value==='all'||r.category===$('category').value));const sales=sum(rows,'sales'),profit=sum(rows,'profit');$('sales').textContent=compact.format(sales);$('profit').textContent=compact.format(profit);$('margin').textContent=(sales?100*profit/sales:0).toFixed(2)+'%';$('lines').textContent=integer.format(sum(rows,'lines'));$('scope').textContent=[$('year').selectedOptions[0].text,$('region').selectedOptions[0].text,$('category').selectedOptions[0].text].join(' · ');regions=group(rows,'region').sort((a,b)=>b.margin-a.margin);const products=group(rows,'subcategory').sort((a,b)=>a.profit-b.profit).slice(0,6);bars('regions',regions,'margin',v=>v.toFixed(2)+'%');bars('products',products,'profit',v=>money.format(v));$('table').replaceChildren();for(const r of regions){const tr=document.createElement('tr');for(const v of [r.name,money.format(r.sales),money.format(r.profit),r.margin.toFixed(2)+'%',integer.format(r.lines)]){const td=document.createElement('td');td.textContent=v;tr.append(td);}$('table').append(tr);}if(!rows.length){$('insight').textContent='No records match this scope. Reset the filters to explore the full sample.';}else if(regions.length>1){const low=regions.at(-1),high=regions[0];$('insight').textContent=`${low.name} has the lowest margin at ${low.margin.toFixed(2)}%, ${(high.margin-low.margin).toFixed(2)} percentage points below ${high.name}. Explore its category and product mix before choosing an intervention.`;}else{const p=products[0];$('insight').textContent=`Within ${regions[0].name}, ${p.name} has the lowest recorded profit (${money.format(p.profit)}). Compare categories to locate the concentration; this pattern alone does not establish its cause.`;}}
for(const id of ['year','region','category'])$(id).addEventListener('change',render);
$('reset').addEventListener('click',()=>{for(const id of ['year','region','category'])$(id).value='all';render();});
$('download').addEventListener('click',()=>{const csv=['Region,Sales,Profit,Margin_pct,Order_lines',...regions.map(r=>[r.name,r.sales.toFixed(2),r.profit.toFixed(2),r.margin.toFixed(4),r.lines].join(','))].join('\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='superstore-regional-scope.csv';a.click();URL.revokeObjectURL(u);});
try{const response=await fetch('data.json');if(!response.ok)throw Error('Data could not be loaded.');data=await response.json();render();}catch(e){$('error').hidden=false;$('error').textContent='The sample data could not be loaded. Please reload the page.';}
